### ISSUE TITLE
Unable to use PointyCastle in Flutter due to dependency for dart:mirrors

### ISSUE THREAD

**Issue by gurmukhp** [PointyCastle/pointycastle#114]
I've imported the package as so:

```
dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: 0.0.4                                       # new
  firebase_auth: 0.1.1                                            # new
  firebase_database: 0.0.12                                       # new
  firebase_storage: 0.0.5                                       # new
  http: '>=0.11.3+12'
  #cipher: "^0.7.1"
  pointycastle: '0.10.0+5'
```

run `flutter packages get`

import the following

```
import 'package:pointycastle/pointycastle.dart';
import 'package:pointycastle/impl.dart';
```

Unfortunately I get the following errors:
```
[VERBOSE-2:dart_error.cc(16)] 'package:reflectable/capability.dart': malformed type: line 539 pos 33: cannot resolve class 'StringInvocation' from '_StringInvocation@457210198'
	class _StringInvocation extends StringInvocation {
	                                ^

Performing full restart...
[VERBOSE-2:dart_error.cc(16)] 'package:reflectable/src/reflectable_mirror_based.dart': error: line 13 pos 1: import of dart:mirrors with --enable-mirrors=false
	import 'dart:mirrors' as dm;
	^
	'package:reflectable/reflectable.dart': error: line 14 pos 1: library handler failed
	import 'src/reflectable_mirror_based.dart' as implementation;
	^
	'package:pointycastle/src/registry/registry.dart': error: line 7 pos 1: library handler failed
	import "package:reflectable/reflectable.dart";
	^
	'package:pointycastle/api.dart': error: line 18 pos 1: library handler failed
	import "src/registry/registry.dart";
	^
	'package:pointycastle/pointycastle.dart': error: line 13 pos 1: library handler failed
	export "package:pointycastle/api.dart";
	^
	'/Users/gurmukh/Library/Developer/CoreSimulator/Devices/EDBF96CD-41AE-4993-B0A0-1CB8E04552A9/data/Containers/Data/Application/157478FE-1B36-4FA2-8986-739CAA2D9421/tmp/crypto-portfoliovkBVyS/crypto-portfolio/lib/main.dart': error: line 9 pos 1: library handler failed
	import 'package:pointycastle/pointycastle.dart';
	^
Restarted app in 622ms.
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
	NoSuchMethodError: The method 'call' was called on null.
	Receiver: null
	Tried calling: call()
	#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
	#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
	#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
	#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

The old cipher package works totally fine. Do you know how I can fix this error?
