### ISSUE TITLE
Flutter  pub get failed . [flutter_test]

### ISSUE THREAD

**Issue by shibingli** [PointyCastle/pointycastle#124]
pub get failed

```
[demo] flutter packages get
Running "flutter packages get" in test...
The current Dart SDK version is 2.0.0-edge.af1436931b93e755d38223c487d33a0a1f5eadf5.

Because every version of flutter_test from sdk depends on args 1.4.2 and analyzer >=0.25.1-alpha.2
  <0.30.0+3 depends on args >=0.12.1 <0.14.0, flutter_test from sdk is incompatible with analyzer
  >=0.25.1-alpha.2 <0.30.0+3.
Because reflectable >=1.0.4 <2.0.0-dev.1.0 requires SDK version >=1.12.0 <2.0.0-dev.infinity and
  reflectable >=1.0.1 <1.0.4 depends on analyzer >=0.27.2 <0.30.0, reflectable >=1.0.1
  <2.0.0-dev.1.0 requires analyzer >=0.27.2 <0.30.0.
Thus, flutter_test from sdk is incompatible with reflectable >=1.0.1 <2.0.0-dev.1.0.
And because pointycastle 0.11.1 depends on reflectable ^1.0.1 and no versions of pointycastle
  match >0.11.1 <0.12.0, flutter_test from sdk is incompatible with pointycastle ^0.11.1.
So, because demo depends on both pointycastle ^0.11.1 and flutter_test any from sdk, version
  solving failed.
pub get failed (1)
exit code 1
```
Flutter version:
```
Flutter 0.4.1-pre.27 • channel master • https://github.com/flutter/flutter.git
Framework • revision 19ad6528e8 (5 天前) • 2018-05-03 07:43:04 +0100
Engine • revision 20b286dd42
Tools • Dart 2.0.0-dev.53.0.flutter-e6d7d67f4b
```

pubspec.yaml:

```
name: demo
description: The is demo App.

dependencies:
  flutter:
    sdk: flutter
  pointycastle: "^0.11.1"

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
   - images/no_title_logo.png
   - images/start_logo.png

```
