### ISSUE TITLE
flutter: unable to install pointycastle 

### ISSUE THREAD

**Issue by attdona** [PointyCastle/pointycastle#139]
Flutter version:

```
Flutter 0.5.7 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 66091f9696 (4 weeks ago) • 2018-07-09 12:52:41 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2

```

My `pubspec.yaml` deps:

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pointycastle: ^0.11.1
```

I've got:

```
Running "flutter packages get" in crypt...                       
Because reflectable >=1.0.4 <=2.0.0-dev.1.0 depends on path >=1.2.0 <1.5.0 and reflectable >=1.0.1 <1.0.4 depends on analyzer >=0.27.2 <0.30.0, reflectable >=1.0.1 <=2.0.0-dev.1.0 requires path >=1.2.0 <1.5.0 or analyzer >=0.27.2 <0.30.0.
And because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2, if reflectable >=1.0.1 <=2.0.0-dev.1.0 and flutter_test any from sdk then path >=1.2.0 <1.5.0.
And because every version of flutter_test from sdk depends on path 1.6.1 and pointycastle >=0.10.0+2 <1.0.0-rc1 depends on reflectable ^1.0.1, flutter_test from sdk is incompatible with pointycastle >=0.10.0+2 <1.0.0-rc1.
So, because crypt depends on both pointycastle ^0.11.1 and flutter_test any from sdk, version solving failed.
pub get failed (1)
```

Is it a way to get ahead?
